routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index')->name('welcome'); 
Route::post('/reservation','ReservationController@reserve')->name('reservation.reserve');
Route::post('/contact', 'ContactController@sendMessage')->name('contact.send');

Auth::routes();




	Route::group(['prefix'=> 'admin','middleware'=>'auth','namespace'=>'admin'], function(){

	Route::get('dashboard', 'DashboardController@index') ->name('admin.dashboard');
	Route::resource('slider', 'SliderController');
	Route::resource('category', 'CategoryController');
	Route::resource('item', 'ItemController');
	Route::get('reservation','ReservationController@index')->name('reservation.index');
	Route::post('reservation/{id}', 'ReservationController@status')->name('reservation.status');
	
	Route::delete('reservation/{id}','ReservationController@destory')->name('reservation.destory');

	Route::get('contact','ContactController@index')->name('contact.index');
	Route::get('contact/{id}','ContactController@show')->name('contact.show');
	Route::delete('contact/{id}','ContactController@destroy')->name('contact.destroy');

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function items(){
    	return $this->hasMany('App\Item');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use\App\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories=Category::all();
        return view('admin.category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required'
            ]);
        $category = new Category();
        $category->name = $request->name;
        $category->slug = str_slug($request->name);
        $category->save();
        return redirect()->route('category.index')->with('successMsg','Category Saved Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category=Category::find($id);
        return view('admin.category.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $this->validate($request,[
            'name' => 'required'
            ]);
         $category=Category::find($id);
         $category->name = $request->name;
         $category->slug = str_slug($request->name);
         $category->save();
         return redirect()->route('category.index')->with('successMsg','Category Updated Successfully .');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         Category::find($id)->delete();
       
        
        return redirect()->back()->with('successMsg','Category Deleted Successfully');
    }
}

resources/views/admin/category/create.blade.php
@extends('layouts.app')

@section('title','slider')

@push('css')



@endpush

@section('content')

	   <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
            @include('layouts.partial.msg')
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">ADD Category</h4>
                  
                </div>
                  <div class="card-body">
                  <div class="card-content">
                    <form method="POST" action="{{ route('category.store') }}" >

                      {{csrf_field()}}
                      <div class="row">
                        <div class="col-md-12">
                          <div class="form-group label-floating">
                            <label class="control-label">Category Name</label>
                            <input type="text" class="form-control" name="name">
                          </div>
                        </div>
                      </div>

                       <div class="row">
                        <div class="col-md-12">
                          <div class="form-group label-floating">
                            <label class="control-label">Slug</label>
                            <input type="text" class="form-control" name="slug">
                          </div>
                        </div>
                      </div>

                      

                      <a href="{{route('category.index')}}" class="btn btn-success">Back</a>
                      <button type="submit" class="btn btn-primary">Save</button>
                    
                  </div>
                </div>
              </div>
            </div>
          
          </div>
        </div>
      </div>


@endsection

@push('scripts')



@endpush

resources/views/admin/category/edit.blade.php
@extends('layouts.app')

@section('title','categoryEdit')

@push('css')



@endpush

@section('content')

	   <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
            @include('layouts.partial.msg')
    
          </div>
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Edit Category</h4>
                  
                </div>
                  <div class="card-body">
                  <div class="card-content">
                    <form method="POST" action="{{ route('category.update',$category->id) }}">

                      {{csrf_field()}}
                      {{ method_field('PUT') }}

                      <div class="row">
                        <div class="col-md-12">
                          <div class="form-group label-floating">
                            <label class="control-label">Category Name</label>
                            <input type="text" class="form-control" name="name" value="{{$category->name}}">
                          </div>
                        </div>
                      </div>

                       

                      <a href="{{route('category.index')}}" class="btn btn-success">Back</a>
                      <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                    
                  </div>
                </div>
              
            
          </div>
        </div>
          </div>
        </div>
      
    



@endsection

@push('scripts')



@endpush

resources/views/admin/category/index.blade.php
@extends('layouts.app')

@section('title','category')

@push('css')
<link rel="stylesheet"href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css">


@endpush

@section('content')

	   <div class="content">
        <div class="container-fluid">
          <div class="row">

            <div class="col-md-12">
              <a href="{{route('category.create')}}" class="btn btn-primary">Add New</a>

              @include('layouts.partial.msg')
            

              <div class="card">

                <div class="card-header card-header-primary">
                  <h4 class="card-title ">All Category</h4>
                  
                </div>
                <div class="card-body">
                  <div class="card-content table-responsive">
                    <table id="table" cellspacing="0"width="100%">
                      <thead class=" text-primary">
                        <th>
                          ID
                        </th>
                        <th>
                          Category Name
                        </th>
                        <th>
                          Slug
                        </th>
                        
                        <th>
                          Created At
                        </th>
                        <th>
                          Updated At
                        </th>
                        <th>
                          Action
                        </th>
                      </thead>
                      <tbody>
                      	@foreach($categories as $key=>$category)

                      	<tr>
                          <td>{{ $key+1 }} </td>

                          <td>{{ $category->name }}</td>
                          <td>{{$category->slug}} </td>
                          
                          <td>{{ $category->created_at }} </td>
                          <td>{{$category->updated_at }} </td>
                           <td>
                            <a href="{{route('category.edit',$category ->id) }}" class="btn btn-info btn-sm"><i class="material-icons">
                           mode_edit</i></a> 

                           <form id="delete-form-{{$category->id}}" action="{{route('category.destroy',$category->id)}}" method="POST" style="display: none;">
                              {{csrf_field()}}
                              {{ method_field('DELETE') }}

                           </form>

                           <button type="button" class="btn btn-danger btn-sm"
                            onclick="if(confirm('Are you sure? You want to delete this?')) {
                           

                              event.preventDefault();
                              document.getElementById('delete-form-{{$category->id}}').submit();
                            } 
                           else
                           {
                            event.preventDefault();
                           }"> 
                            <i class="material-icons">delete</i>
                          </button>
                         </td>
                        </tr>
                        @endforeach
                            
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          
          </div>
        </div>
      </div>


@endsection

@push('scripts')

<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>


<script>
  $(document).ready(function() {
    $('#table').DataTable();
} );
</script>

@endpush